
-----------------------------------------------------------------------------
-- SECURITY_PRINCIPAL
-----------------------------------------------------------------------------

CREATE TABLE SECURITY_PRINCIPAL
(
    PRINCIPAL_ID int4 NOT NULL,
    CLASSNAME varchar(254) NOT NULL,
    IS_MAPPING_ONLY int2 NOT NULL,
    IS_ENABLED int2 NOT NULL,
    FULL_PATH varchar(254) NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL,
    MODIFIED_DATE TIMESTAMP NOT NULL,
    CONSTRAINT UIX_SECURITY_PRINCIPAL UNIQUE (FULL_PATH)
);

ALTER TABLE SECURITY_PRINCIPAL
    ADD CONSTRAINT SECURITY_PRINCIPAL_PK
PRIMARY KEY (PRINCIPAL_ID);






-----------------------------------------------------------------------------
-- SECURITY_PERMISSION
-----------------------------------------------------------------------------

CREATE TABLE SECURITY_PERMISSION
(
    PERMISSION_ID int4 NOT NULL,
    CLASSNAME varchar(254) NOT NULL,
    NAME varchar(254) NOT NULL,
    ACTIONS varchar(254) NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL,
    MODIFIED_DATE TIMESTAMP NOT NULL
);

ALTER TABLE SECURITY_PERMISSION
    ADD CONSTRAINT SECURITY_PERMISSION_PK
PRIMARY KEY (PERMISSION_ID);






-----------------------------------------------------------------------------
-- PRINCIPAL_PERMISSION
-----------------------------------------------------------------------------

CREATE TABLE PRINCIPAL_PERMISSION
(
    PRINCIPAL_ID int4 NOT NULL,
    PERMISSION_ID int4 NOT NULL
);

ALTER TABLE PRINCIPAL_PERMISSION
    ADD CONSTRAINT PRINCIPAL_PERMISSION_PK
PRIMARY KEY (PRINCIPAL_ID,PERMISSION_ID);






-----------------------------------------------------------------------------
-- SECURITY_CREDENTIAL
-----------------------------------------------------------------------------

CREATE TABLE SECURITY_CREDENTIAL
(
    CREDENTIAL_ID int4 NOT NULL,
    PRINCIPAL_ID int4 NOT NULL,
    COLUMN_VALUE varchar(254) NOT NULL,
    TYPE int4 NOT NULL,
    CLASSNAME varchar(254),
    UPDATE_REQUIRED int2 NOT NULL,
    IS_ENCODED int2 NOT NULL,
    IS_ENABLED int2 NOT NULL,
    AUTH_FAILURES int4 NOT NULL,
    IS_EXPIRED int2 NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL,
    MODIFIED_DATE TIMESTAMP NOT NULL,
    PREV_AUTH_DATE TIMESTAMP,
    LAST_AUTH_DATE TIMESTAMP,
    EXPIRATION_DATE DATE
);

ALTER TABLE SECURITY_CREDENTIAL
    ADD CONSTRAINT SECURITY_CREDENTIAL_PK
PRIMARY KEY (CREDENTIAL_ID);






-----------------------------------------------------------------------------
-- SSO_SITE
-----------------------------------------------------------------------------

CREATE TABLE SSO_SITE
(
    SITE_ID int4 NOT NULL,
    NAME varchar(254) NOT NULL,
    URL varchar(254) NOT NULL,
    ALLOW_USER_SET int2 default 0,
    REQUIRES_CERTIFICATE int2 default 0,
    CHALLENGE_RESPONSE_AUTH int2 default 0,
    FORM_AUTH int2 default 0,
    FORM_USER_FIELD varchar(128),
    FORM_PWD_FIELD varchar(128),
    REALM varchar(128),
    CONSTRAINT UIX_SITE_URL UNIQUE (URL)
);

ALTER TABLE SSO_SITE
    ADD CONSTRAINT SSO_SITE_PK
PRIMARY KEY (SITE_ID);






-----------------------------------------------------------------------------
-- SSO_COOKIE
-----------------------------------------------------------------------------

CREATE TABLE SSO_COOKIE
(
    COOKIE_ID int4 NOT NULL,
    COOKIE varchar(1024) NOT NULL,
    CREATE_DATE TIMESTAMP NOT NULL
);

ALTER TABLE SSO_COOKIE
    ADD CONSTRAINT SSO_COOKIE_PK
PRIMARY KEY (COOKIE_ID);






-----------------------------------------------------------------------------
-- SSO_SITE_TO_PRINCIPALS
-----------------------------------------------------------------------------

CREATE TABLE SSO_SITE_TO_PRINCIPALS
(
    SITE_ID int4 NOT NULL,
    PRINCIPAL_ID int4 NOT NULL
);

ALTER TABLE SSO_SITE_TO_PRINCIPALS
    ADD CONSTRAINT SSO_SITE_TO_PRINCIPALS_PK
PRIMARY KEY (SITE_ID,PRINCIPAL_ID);






-----------------------------------------------------------------------------
-- SSO_PRINCIPAL_TO_REMOTE
-----------------------------------------------------------------------------

CREATE TABLE SSO_PRINCIPAL_TO_REMOTE
(
    PRINCIPAL_ID int4 NOT NULL,
    REMOTE_PRINCIPAL_ID int4 NOT NULL
);

ALTER TABLE SSO_PRINCIPAL_TO_REMOTE
    ADD CONSTRAINT SSO_PRINCIPAL_TO_REMOTE_PK
PRIMARY KEY (PRINCIPAL_ID,REMOTE_PRINCIPAL_ID);






-----------------------------------------------------------------------------
-- SSO_SITE_TO_REMOTE
-----------------------------------------------------------------------------

CREATE TABLE SSO_SITE_TO_REMOTE
(
    SITE_ID int4 NOT NULL,
    PRINCIPAL_ID int4 NOT NULL
);

ALTER TABLE SSO_SITE_TO_REMOTE
    ADD CONSTRAINT SSO_SITE_TO_REMOTE_PK
PRIMARY KEY (SITE_ID,PRINCIPAL_ID);






-----------------------------------------------------------------------------
-- SSO_COOKIE_TO_REMOTE
-----------------------------------------------------------------------------

CREATE TABLE SSO_COOKIE_TO_REMOTE
(
    COOKIE_ID int4 NOT NULL,
    REMOTE_PRINCIPAL_ID int4 NOT NULL
);

ALTER TABLE SSO_COOKIE_TO_REMOTE
    ADD CONSTRAINT SSO_COOKIE_TO_REMOTE_PK
PRIMARY KEY (COOKIE_ID,REMOTE_PRINCIPAL_ID);






-----------------------------------------------------------------------------
-- SECURITY_USER_ROLE
-----------------------------------------------------------------------------

CREATE TABLE SECURITY_USER_ROLE
(
    USER_ID int4 NOT NULL,
    ROLE_ID int4 NOT NULL
);

ALTER TABLE SECURITY_USER_ROLE
    ADD CONSTRAINT SECURITY_USER_ROLE_PK
PRIMARY KEY (USER_ID,ROLE_ID);






-----------------------------------------------------------------------------
-- SECURITY_USER_GROUP
-----------------------------------------------------------------------------

CREATE TABLE SECURITY_USER_GROUP
(
    USER_ID int4 NOT NULL,
    GROUP_ID int4 NOT NULL
);

ALTER TABLE SECURITY_USER_GROUP
    ADD CONSTRAINT SECURITY_USER_GROUP_PK
PRIMARY KEY (USER_ID,GROUP_ID);






-----------------------------------------------------------------------------
-- SECURITY_GROUP_ROLE
-----------------------------------------------------------------------------

CREATE TABLE SECURITY_GROUP_ROLE
(
    GROUP_ID int4 NOT NULL,
    ROLE_ID int4 NOT NULL
);

ALTER TABLE SECURITY_GROUP_ROLE
    ADD CONSTRAINT SECURITY_GROUP_ROLE_PK
PRIMARY KEY (GROUP_ID,ROLE_ID);









ALTER TABLE PRINCIPAL_PERMISSION
    ADD CONSTRAINT PRINCIPAL_PERMISSION_FK_1 FOREIGN KEY (PERMISSION_ID)
    REFERENCES SECURITY_PERMISSION (PERMISSION_ID)
ON DELETE CASCADE
;

ALTER TABLE PRINCIPAL_PERMISSION
    ADD CONSTRAINT PRINCIPAL_PERMISSION_FK_2 FOREIGN KEY (PRINCIPAL_ID)
    REFERENCES SECURITY_PRINCIPAL (PRINCIPAL_ID)
ON DELETE CASCADE
;



ALTER TABLE SECURITY_CREDENTIAL
    ADD CONSTRAINT SECURITY_CREDENTIAL_FK_1 FOREIGN KEY (PRINCIPAL_ID)
    REFERENCES SECURITY_PRINCIPAL (PRINCIPAL_ID)
ON DELETE CASCADE
;







ALTER TABLE SSO_SITE_TO_PRINCIPALS
    ADD CONSTRAINT SSO_SITE_TO_PRINCIPALS_FK_1 FOREIGN KEY (SITE_ID)
    REFERENCES SSO_SITE (SITE_ID)
ON DELETE CASCADE
;

ALTER TABLE SSO_SITE_TO_PRINCIPALS
    ADD CONSTRAINT SSO_SITE_TO_PRINCIPALS_FK_2 FOREIGN KEY (PRINCIPAL_ID)
    REFERENCES SECURITY_PRINCIPAL (PRINCIPAL_ID)
ON DELETE CASCADE
;



ALTER TABLE SSO_PRINCIPAL_TO_REMOTE
    ADD CONSTRAINT SSO_PRINCIPAL_TO_REMOTE_FK_1 FOREIGN KEY (PRINCIPAL_ID)
    REFERENCES SECURITY_PRINCIPAL (PRINCIPAL_ID)
ON DELETE CASCADE
;

ALTER TABLE SSO_PRINCIPAL_TO_REMOTE
    ADD CONSTRAINT SSO_PRINCIPAL_TO_REMOTE_FK_2 FOREIGN KEY (REMOTE_PRINCIPAL_ID)
    REFERENCES SECURITY_PRINCIPAL (PRINCIPAL_ID)
ON DELETE CASCADE
;



ALTER TABLE SSO_SITE_TO_REMOTE
    ADD CONSTRAINT SSO_SITE_TO_REMOTE_FK_1 FOREIGN KEY (SITE_ID)
    REFERENCES SSO_SITE (SITE_ID)
ON DELETE CASCADE
;

ALTER TABLE SSO_SITE_TO_REMOTE
    ADD CONSTRAINT SSO_SITE_TO_REMOTE_FK_2 FOREIGN KEY (PRINCIPAL_ID)
    REFERENCES SECURITY_PRINCIPAL (PRINCIPAL_ID)
ON DELETE CASCADE
;



ALTER TABLE SSO_COOKIE_TO_REMOTE
    ADD CONSTRAINT SSO_COOKIE_TO_REMOTE_FK_1 FOREIGN KEY (COOKIE_ID)
    REFERENCES SSO_COOKIE (COOKIE_ID)
ON DELETE CASCADE
;

ALTER TABLE SSO_COOKIE_TO_REMOTE
    ADD CONSTRAINT SSO_COOKIE_TO_REMOTE_FK_2 FOREIGN KEY (REMOTE_PRINCIPAL_ID)
    REFERENCES SECURITY_PRINCIPAL (PRINCIPAL_ID)
ON DELETE CASCADE
;



ALTER TABLE SECURITY_USER_ROLE
    ADD CONSTRAINT SECURITY_USER_ROLE_FK_1 FOREIGN KEY (ROLE_ID)
    REFERENCES SECURITY_PRINCIPAL (PRINCIPAL_ID)
ON DELETE CASCADE
;

ALTER TABLE SECURITY_USER_ROLE
    ADD CONSTRAINT SECURITY_USER_ROLE_FK_2 FOREIGN KEY (USER_ID)
    REFERENCES SECURITY_PRINCIPAL (PRINCIPAL_ID)
ON DELETE CASCADE
;



ALTER TABLE SECURITY_USER_GROUP
    ADD CONSTRAINT SECURITY_USER_GROUP_FK_1 FOREIGN KEY (GROUP_ID)
    REFERENCES SECURITY_PRINCIPAL (PRINCIPAL_ID)
ON DELETE CASCADE
;

ALTER TABLE SECURITY_USER_GROUP
    ADD CONSTRAINT SECURITY_USER_GROUP_FK_2 FOREIGN KEY (USER_ID)
    REFERENCES SECURITY_PRINCIPAL (PRINCIPAL_ID)
ON DELETE CASCADE
;



ALTER TABLE SECURITY_GROUP_ROLE
    ADD CONSTRAINT SECURITY_GROUP_ROLE_FK_1 FOREIGN KEY (GROUP_ID)
    REFERENCES SECURITY_PRINCIPAL (PRINCIPAL_ID)
ON DELETE CASCADE
;

ALTER TABLE SECURITY_GROUP_ROLE
    ADD CONSTRAINT SECURITY_GROUP_ROLE_FK_2 FOREIGN KEY (ROLE_ID)
    REFERENCES SECURITY_PRINCIPAL (PRINCIPAL_ID)
ON DELETE CASCADE
;



