
DROP TABLE METADATA_FIELDS IF EXISTS;
DROP TABLE PARAMETER IF EXISTS; 
DROP TABLE PORTLET_CONTENT_TYPE IF EXISTS; 
DROP TABLE LANGUAGE IF EXISTS; 
DROP TABLE PORTLET_DEFINITION IF EXISTS; 
DROP TABLE WEB_APPLICATION IF EXISTS; 
DROP TABLE PORTLET_APPLICATION IF EXISTS; 
DROP TABLE PORTLET_PREFERENCE IF EXISTS; 
DROP TABLE PREFERENCE_VALUE IF EXISTS; 
DROP TABLE USER_PREFERENCE_VALUE IF EXISTS; 
DROP TABLE PORTLET_ENTITY IF EXISTS; 
DROP TABLE LOCALIZED_DESCRIPTION IF EXISTS; 
DROP TABLE LOCALIZED_DISPLAY_NAME IF EXISTS; 
DROP TABLE SECURITY_ROLE_REFERENCE IF EXISTS;

