DROP TABLE SECURITY_USER_ROLE IF EXISTS;
DROP TABLE SECURITY_USER_GROUP IF EXISTS;
DROP TABLE SECURITY_GROUP_ROLE IF EXISTS;
DROP TABLE SECURITY_PRINCIPAL_PERMISSION IF EXISTS;
DROP TABLE SECURITY_PERMISSION IF EXISTS;
DROP TABLE SECURITY_CREDENTIAL IF EXISTS;
DROP TABLE SECURITY_PRINCIPAL IF EXISTS;

