drop table A;
drop table B;

drop table OJB_HL_SEQ;
drop table OJB_LOCKENTRY;
drop table OJB_NRM;
drop table OJB_DLIST;
drop table OJB_DLIST_ENTRIES;
drop table OJB_DSET;
drop table OJB_DSET_ENTRIES;
drop table OJB_DMAP;


DROP TABLE CAPABILITY;
DROP TABLE MIMETYPE;
DROP TABLE CLIENT;
DROP TABLE MEDIA_TYPE;

DROP TABLE CLIENT_TO_CAPABILITY;
DROP TABLE CLIENT_TO_MIMETYPE;
DROP TABLE MEDIATYPE_TO_CAPABILITY;
DROP TABLE MEDIATYPE_TO_MIMETYPE;

DROP TABLE PAGE_SEC_CONSTRAINTS_REF;
DROP TABLE PAGE_SEC_CONSTRAINT_DEF;
DROP TABLE PAGE_SEC_CONSTRAINTS_DEF;
DROP TABLE PAGE_SECURITY;
DROP TABLE FRAGMENT_PREF_VALUE;
DROP TABLE FRAGMENT_PREF;
DROP TABLE FRAGMENT_CONSTRAINTS_REF;
DROP TABLE FRAGMENT_CONSTRAINT;
DROP TABLE FRAGMENT;
DROP TABLE PAGE_MENU_METADATA;
DROP TABLE PAGE_MENU;
DROP TABLE PAGE_CONSTRAINTS_REF;
DROP TABLE PAGE_CONSTRAINT;
DROP TABLE PAGE_METADATA;
DROP TABLE PAGE;
DROP TABLE FOLDER_MENU_METADATA;
DROP TABLE FOLDER_MENU;
DROP TABLE FOLDER_ORDER;
DROP TABLE FOLDER_CONSTRAINTS_REF;
DROP TABLE FOLDER_CONSTRAINT;
DROP TABLE FOLDER_METADATA;
DROP TABLE FOLDER;

DROP TABLE RULE_CRITERION;
DROP TABLE PRINCIPAL_RULE_ASSOC;
DROP TABLE PROFILE_PAGE_ASSOC;
DROP TABLE PROFILING_RULE;

-----------------------------------------------------------------------------
-- drop preferences schema
-----------------------------------------------------------------------------
drop table PREFS_PROPERTY_VALUE;
drop table PREFS_NODE_PROPERTY_KEY;
drop table PREFS_PROPERTY_KEY;
drop table PREFS_NODE;

DROP TABLE PA_METADATA_FIELDS;
DROP TABLE PD_METADATA_FIELDS;
DROP TABLE LANGUAGE; 
DROP TABLE PORTLET_CONTENT_TYPE; 
DROP TABLE PARAMETER; 
DROP TABLE PORTLET_ENTITY; 
DROP TABLE SECURITY_ROLE_REFERENCE;
DROP TABLE SECURITY_ROLE;
DROP TABLE USER_ATTRIBUTE_REF;
DROP TABLE USER_ATTRIBUTE;
DROP TABLE JETSPEED_SERVICE;

DROP TABLE LOCALIZED_DESCRIPTION; 
DROP TABLE LOCALIZED_DISPLAY_NAME; 

DROP TABLE WEB_APPLICATION; 
DROP TABLE PORTLET_DEFINITION; 
DROP TABLE PORTLET_APPLICATION; 

drop table PRINCIPAL_PERMISSION;
DROP TABLE SECURITY_CREDENTIAL;
drop table SSO_SITE_TO_PRINCIPALS;
drop table SSO_PRINCIPAL_TO_REMOTE;
drop table SSO_SITE_TO_REMOTE;
DROP TABLE SECURITY_USER_ROLE;
DROP TABLE SECURITY_USER_GROUP;
DROP TABLE SECURITY_GROUP_ROLE;


drop table SSO_SITE;
drop table SECURITY_PERMISSION;
drop table SECURITY_PRINCIPAL;

