DROP TABLE SECURITY IF EXISTS 
DROP TABLE SKIN IF EXISTS 
DROP TABLE CONTROL IF EXISTS 
DROP TABLE LAYOUT IF EXISTS 
DROP TABLE PSML_ENTRY IF EXISTS 
DROP TABLE PSML IF EXISTS 

DROP TABLE PARAMETER IF EXISTS 
DROP TABLE PORTLET_CONTENT_TYPE IF EXISTS 
DROP TABLE LANGUAGE IF EXISTS 
DROP TABLE PORTLET_DEFINITION IF EXISTS 
DROP TABLE WEB_APPLICATION IF EXISTS 
DROP TABLE PORTLET_APPLICATION IF EXISTS 
DROP TABLE PORTLET_PREFERENCE IF EXISTS 
DROP TABLE PREFERENCE_VALUE IF EXISTS 

DROP TABLE OJB_HL_SEQ IF EXISTS 
DROP TABLE OJB_LOCKENTRY IF EXISTS 
DROP TABLE OJB_NRM IF EXISTS 
DROP TABLE OJB_DLIST IF EXISTS 
DROP TABLE OJB_DLIST_ENTRIES IF EXISTS 
DROP TABLE OJB_DSET IF EXISTS 
DROP TABLE OJB_DSET_ENTRIES IF EXISTS 
DROP TABLE OJB_DMAP IF EXISTS 
DROP TABLE OJB_DMAP_ENTRIES IF EXISTS 

DROP TABLE LOCALIZED_DESCRITPION IF EXISTS 
DROP TABLE LOCALIZED_DISPLAY_NAME IF EXISTS 


