DROP TABLE SECURITY IF EXISTS 
DROP TABLE SKIN IF EXISTS 
DROP TABLE CONTROL IF EXISTS 
DROP TABLE LAYOUT IF EXISTS 
DROP TABLE PSML_ENTRY IF EXISTS 
DROP TABLE PSML IF EXISTS 

DROP TABLE PARAMETER IF EXISTS 
DROP TABLE PORTLET_CONTENT_TYPE IF EXISTS 
DROP TABLE LANGUAGE IF EXISTS 
DROP TABLE PORTLET_DEFINITION IF EXISTS 
DROP TABLE WEB_APPLICATION IF EXISTS 
DROP TABLE PORTLET_APPLICATION IF EXISTS 
DROP TABLE PORTLET_PREFERENCE IF EXISTS 
DROP TABLE PREFERENCE_VALUE IF EXISTS 
DROP TABLE USER_PORTLET_PREFERENCE IF EXISTS 
DROP TABLE USER_PREFERENCE_VALUE IF EXISTS 
DROP TABLE PORTLET_ENTITY IF EXISTS 
DROP TABLE LOCALIZED_DESCRIPTION IF EXISTS 
DROP TABLE LOCALIZED_DISPLAY_NAME IF EXISTS 
DROP TABLE SECURITY_ROLE_REFERENCE IF EXISTS

DROP TABLE OJB_HL_SEQ IF EXISTS 
DROP TABLE OJB_LOCKENTRY IF EXISTS 
DROP TABLE OJB_NRM IF EXISTS 
DROP TABLE OJB_DLIST IF EXISTS 
DROP TABLE OJB_DLIST_ENTRIES IF EXISTS 
DROP TABLE OJB_DSET IF EXISTS 
DROP TABLE OJB_DSET_ENTRIES IF EXISTS 
DROP TABLE OJB_DMAP IF EXISTS 
DROP TABLE OJB_DMAP_ENTRIES IF EXISTS

DROP TABLE CAPABILITY IF EXISTS
DROP TABLE MIMETYPE IF EXISTS
DROP TABLE CLIENT IF EXISTS
DROP TABLE MEDIA_TYPE IF EXISTS

DROP TABLE CLIENT_TO_CAPABILITY IF EXISTS
DROP TABLE CLIENT_TO_MIMETYPE IF EXISTS
DROP TABLE MEDIATYPE_TO_CAPABILITY IF EXISTS
DROP TABLE MEDIATYPE_TO_MIMETYPE IF EXISTS




