-- this is a temporary script to populate entities for the XML Page Registry
INSERT INTO PORTLET_ENTITY (ID, PORTLET_DEFINITION_ID) 
  VALUES (1, SELECT ID FROM PORTLET_DEFINITION WHERE NAME = 'TwoColumns');
INSERT INTO PORTLET_ENTITY (ID, PORTLET_DEFINITION_ID) 
  VALUES (2, SELECT ID FROM PORTLET_DEFINITION WHERE NAME = 'VelocityTwoColumns');
INSERT INTO PORTLET_ENTITY (ID, PORTLET_DEFINITION_ID) 
  VALUES (3, SELECT ID FROM PORTLET_DEFINITION WHERE NAME = 'HelloPortlet');
INSERT INTO PORTLET_ENTITY (ID, PORTLET_DEFINITION_ID) 
  VALUES (4, SELECT ID FROM PORTLET_DEFINITION WHERE NAME = 'JMXPortlet');
INSERT INTO PORTLET_ENTITY (ID, PORTLET_DEFINITION_ID) 
  VALUES (5, SELECT ID FROM PORTLET_DEFINITION WHERE NAME = 'PreferencePortlet');
INSERT INTO PORTLET_ENTITY (ID, PORTLET_DEFINITION_ID) 
  VALUES (6, SELECT ID FROM PORTLET_DEFINITION WHERE NAME = 'DisplayRequestPortlet');
INSERT INTO PORTLET_ENTITY (ID, PORTLET_DEFINITION_ID) 
  VALUES (7, SELECT ID FROM PORTLET_DEFINITION WHERE NAME = 'PickANumberPortlet');
INSERT INTO PORTLET_ENTITY (ID, PORTLET_DEFINITION_ID) 
  VALUES (8, SELECT ID FROM PORTLET_DEFINITION WHERE NAME = 'AttributeScopePortlet');
INSERT INTO PORTLET_ENTITY (ID, PORTLET_DEFINITION_ID) 
  VALUES (9, SELECT ID FROM PORTLET_DEFINITION WHERE NAME = 'CustomerList');
INSERT INTO PORTLET_ENTITY (ID, PORTLET_DEFINITION_ID) 
  VALUES (10, SELECT ID FROM PORTLET_DEFINITION WHERE NAME = 'CustomerInfo');
INSERT INTO PORTLET_ENTITY (ID, PORTLET_DEFINITION_ID) 
  VALUES (11, SELECT ID FROM PORTLET_DEFINITION WHERE NAME = 'CustomerDetail');
INSERT INTO PORTLET_ENTITY (ID, PORTLET_DEFINITION_ID) 
  VALUES (12, SELECT ID FROM PORTLET_DEFINITION WHERE NAME = 'LoginPortlet');
INSERT INTO PORTLET_ENTITY (ID, PORTLET_DEFINITION_ID) 
  VALUES (13, SELECT ID FROM PORTLET_DEFINITION WHERE NAME = 'PortletApplicationBrowser');
