INSERT INTO PORTLET_ENTITY (OID, PORTLET_DEFINITION_ID, ID) 
  VALUES (1, 1, '1');
INSERT INTO PORTLET_ENTITY (OID, PORTLET_DEFINITION_ID, ID) 
  VALUES (2, 2, '2');
INSERT INTO PORTLET_ENTITY (OID, PORTLET_DEFINITION_ID, ID) 
  VALUES (3, 21, '3');
INSERT INTO PORTLET_ENTITY (OID, PORTLET_DEFINITION_ID, ID) 
  VALUES (4, 22, '4');
INSERT INTO PORTLET_ENTITY (OID, PORTLET_DEFINITION_ID, ID) 
  VALUES (5, 23, '5');
INSERT INTO PORTLET_ENTITY (OID, PORTLET_DEFINITION_ID, ID) 
  VALUES (6, 24, '6');
INSERT INTO PORTLET_ENTITY (OID, PORTLET_DEFINITION_ID, ID) 
  VALUES (7, 25, '7');
INSERT INTO PORTLET_ENTITY (OID, PORTLET_DEFINITION_ID, ID) 
  VALUES (8, 26, '8');
INSERT INTO PORTLET_ENTITY (OID, PORTLET_DEFINITION_ID, ID) 
  VALUES (9, 27, '9');
INSERT INTO PORTLET_ENTITY (OID, PORTLET_DEFINITION_ID, ID) 
  VALUES (10, 28, '10');
INSERT INTO PORTLET_ENTITY (OID, PORTLET_DEFINITION_ID, ID) 
  VALUES (11, 29, '11');
INSERT INTO PORTLET_ENTITY (OID, PORTLET_DEFINITION_ID, ID) 
  VALUES (12, 61, '12');
INSERT INTO PORTLET_ENTITY (OID, PORTLET_DEFINITION_ID, ID) 
  VALUES (13, 3, '13');
INSERT INTO PORTLET_ENTITY (OID, PORTLET_DEFINITION_ID, ID) 
  VALUES (14, 4, '14');
INSERT INTO PORTLET_ENTITY (OID, PORTLET_DEFINITION_ID, ID)
  VALUES (15, 41, '15');
